// Comprehensive list of major Indian Railway stations (IRCTC).
// Covers metros, state capitals, junctions, and popular tourist/pilgrim hubs.
export const STATIONS: { code: string; name: string }[] = [
  // Delhi NCR
  { code: "NDLS", name: "New Delhi" },
  { code: "DLI", name: "Delhi Junction (Old Delhi)" },
  { code: "NZM", name: "Hazrat Nizamuddin" },
  { code: "ANVT", name: "Anand Vihar Terminal" },
  { code: "DEE", name: "Delhi Sarai Rohilla" },
  { code: "DSA", name: "Delhi Shahdara" },
  { code: "GZB", name: "Ghaziabad" },
  { code: "FDB", name: "Faridabad" },
  { code: "GGN", name: "Gurgaon" },
  { code: "NUR", name: "Noida (Dadri)" },

  // Mumbai & Maharashtra
  { code: "CSMT", name: "Mumbai CSMT" },
  { code: "BCT", name: "Mumbai Central" },
  { code: "MMCT", name: "Mumbai Central Terminus" },
  { code: "LTT", name: "Lokmanya Tilak Terminus" },
  { code: "BDTS", name: "Bandra Terminus" },
  { code: "DR", name: "Dadar" },
  { code: "TNA", name: "Thane" },
  { code: "KYN", name: "Kalyan Jn" },
  { code: "PUNE", name: "Pune Junction" },
  { code: "NGP", name: "Nagpur" },
  { code: "NK", name: "Nashik Road" },
  { code: "SUR", name: "Solapur Jn" },
  { code: "KOP", name: "Kolhapur (CSMT)" },
  { code: "AK", name: "Akola Jn" },
  { code: "BSL", name: "Bhusaval Jn" },
  { code: "MMR", name: "Manmad Jn" },
  { code: "AWB", name: "Aurangabad" },
  { code: "RTM", name: "Ratlam Jn" },

  // Gujarat
  { code: "ADI", name: "Ahmedabad Jn" },
  { code: "ST", name: "Surat" },
  { code: "BRC", name: "Vadodara Jn" },
  { code: "RJT", name: "Rajkot Jn" },
  { code: "BVC", name: "Bhavnagar Terminus" },
  { code: "JAM", name: "Jamnagar" },
  { code: "OKHA", name: "Okha" },
  { code: "DWK", name: "Dwarka" },
  { code: "PBR", name: "Porbandar" },
  { code: "GIMB", name: "Gandhidham" },
  { code: "BVI", name: "Bharuch" },

  // Rajasthan
  { code: "JP", name: "Jaipur" },
  { code: "JU", name: "Jodhpur Jn" },
  { code: "JSM", name: "Jaisalmer" },
  { code: "UDZ", name: "Udaipur City" },
  { code: "AII", name: "Ajmer Jn" },
  { code: "BKN", name: "Bikaner Jn" },
  { code: "KOTA", name: "Kota Jn" },
  { code: "ABR", name: "Abu Road" },
  { code: "BTE", name: "Bharatpur Jn" },
  { code: "ALWR", name: "Alwar" },
  { code: "SWM", name: "Sawai Madhopur" },

  // Uttar Pradesh
  { code: "LKO", name: "Lucknow (Charbagh)" },
  { code: "LJN", name: "Lucknow Jn (NER)" },
  { code: "CNB", name: "Kanpur Central" },
  { code: "BSB", name: "Varanasi Jn" },
  { code: "BSBS", name: "Banaras (Manduadih)" },
  { code: "PRYJ", name: "Prayagraj Jn" },
  { code: "AGC", name: "Agra Cantt" },
  { code: "AF", name: "Agra Fort" },
  { code: "MTJ", name: "Mathura Jn" },
  { code: "BE", name: "Bareilly" },
  { code: "MB", name: "Moradabad" },
  { code: "GKP", name: "Gorakhpur" },
  { code: "AY", name: "Ayodhya Cantt" },
  { code: "AYC", name: "Ayodhya Jn" },
  { code: "MUV", name: "Manduadih" },
  { code: "JHS", name: "Jhansi Jn" },
  { code: "BSBE", name: "Etawah" },
  { code: "ALD", name: "Allahabad (Prayagraj)" },
  { code: "MGS", name: "Mughal Sarai (DDU)" },
  { code: "DDU", name: "Pt Deen Dayal Upadhyaya Jn" },
  { code: "SLN", name: "Sultanpur" },
  { code: "FZD", name: "Faizabad Jn" },
  { code: "AMH", name: "Azamgarh" },

  // Madhya Pradesh
  { code: "BPL", name: "Bhopal Jn" },
  { code: "HBJ", name: "Habibganj (Rani Kamlapati)" },
  { code: "INDB", name: "Indore Jn" },
  { code: "JBP", name: "Jabalpur" },
  { code: "GWL", name: "Gwalior" },
  { code: "UJN", name: "Ujjain Jn" },
  { code: "STA", name: "Satna" },
  { code: "REWA", name: "Rewa" },
  { code: "KTE", name: "Katni" },
  { code: "BINA", name: "Bina Jn" },

  // Bihar & Jharkhand
  { code: "PNBE", name: "Patna Jn" },
  { code: "RJPB", name: "Rajendra Nagar Terminal" },
  { code: "GAYA", name: "Gaya Jn" },
  { code: "MFP", name: "Muzaffarpur Jn" },
  { code: "BJU", name: "Barauni Jn" },
  { code: "DBG", name: "Darbhanga Jn" },
  { code: "BGP", name: "Bhagalpur" },
  { code: "RNC", name: "Ranchi Jn" },
  { code: "TATA", name: "Tatanagar Jn" },
  { code: "DHN", name: "Dhanbad Jn" },
  { code: "BKSC", name: "Bokaro Steel City" },
  { code: "JSME", name: "Jasidih Jn" },
  { code: "PPTA", name: "Patliputra" },

  // West Bengal & North East
  { code: "HWH", name: "Howrah Jn" },
  { code: "SDAH", name: "Sealdah" },
  { code: "KOAA", name: "Kolkata" },
  { code: "SHM", name: "Shalimar" },
  { code: "SRC", name: "Santragachi Jn" },
  { code: "KGP", name: "Kharagpur Jn" },
  { code: "ASN", name: "Asansol Jn" },
  { code: "DGR", name: "Durgapur" },
  { code: "BWN", name: "Barddhaman Jn" },
  { code: "NJP", name: "New Jalpaiguri" },
  { code: "SGUJ", name: "Siliguri Jn" },
  { code: "DBRT", name: "Dibrugarh Town" },
  { code: "DBRG", name: "Dibrugarh" },
  { code: "GHY", name: "Guwahati" },
  { code: "KYQ", name: "Kamakhya" },
  { code: "DMV", name: "Dimapur" },
  { code: "AGTL", name: "Agartala" },
  { code: "JRH", name: "Jorhat Town" },
  { code: "RNY", name: "Rangiya Jn" },

  // Odisha
  { code: "BBS", name: "Bhubaneswar" },
  { code: "PURI", name: "Puri" },
  { code: "CTC", name: "Cuttack" },
  { code: "BAM", name: "Brahmapur" },
  { code: "KUR", name: "Khurda Road Jn" },
  { code: "SBP", name: "Sambalpur" },
  { code: "BLS", name: "Balasore" },
  { code: "ANGL", name: "Angul" },
  { code: "JJKR", name: "Jajpur K Road" },

  // Chhattisgarh
  { code: "R", name: "Raipur Jn" },
  { code: "BSP", name: "Bilaspur Jn" },
  { code: "DURG", name: "Durg" },
  { code: "G", name: "Gondia Jn" },
  { code: "RIG", name: "Raigarh" },
  { code: "JDB", name: "Jagdalpur" },

  // Andhra Pradesh & Telangana
  { code: "HYB", name: "Hyderabad Deccan" },
  { code: "SC", name: "Secunderabad Jn" },
  { code: "KCG", name: "Kacheguda" },
  { code: "BZA", name: "Vijayawada Jn" },
  { code: "VSKP", name: "Visakhapatnam" },
  { code: "TPTY", name: "Tirupati" },
  { code: "GNT", name: "Guntur Jn" },
  { code: "RJY", name: "Rajahmundry" },
  { code: "NLR", name: "Nellore" },
  { code: "WL", name: "Warangal" },
  { code: "KZJ", name: "Kazipet Jn" },
  { code: "NED", name: "Nanded" },
  { code: "AWB-S", name: "Anantapur" },
  { code: "KRNT", name: "Kurnool City" },
  { code: "DMM", name: "Dharmavaram Jn" },
  { code: "RU", name: "Renigunta Jn" },
  { code: "OGL", name: "Ongole" },

  // Karnataka
  { code: "SBC", name: "KSR Bengaluru (City)" },
  { code: "YPR", name: "Yesvantpur Jn" },
  { code: "BNC", name: "Bangalore Cantt" },
  { code: "KJM", name: "Krishnarajapuram" },
  { code: "SMET", name: "Sir M Visvesvaraya Terminal" },
  { code: "MYS", name: "Mysuru Jn" },
  { code: "UBL", name: "Hubballi Jn" },
  { code: "BGM", name: "Belagavi" },
  { code: "MAJN", name: "Mangaluru Jn" },
  { code: "MAQ", name: "Mangaluru Central" },
  { code: "GDG", name: "Gadag Jn" },
  { code: "BAY", name: "Ballari Jn" },
  { code: "DVG", name: "Davangere" },
  { code: "ASK", name: "Arsikere Jn" },
  { code: "TK", name: "Tumakuru" },

  // Tamil Nadu
  { code: "MAS", name: "Chennai Central (MGR)" },
  { code: "MS", name: "Chennai Egmore" },
  { code: "TBM", name: "Tambaram" },
  { code: "MSB", name: "Chennai Beach" },
  { code: "CBE", name: "Coimbatore Jn" },
  { code: "MDU", name: "Madurai Jn" },
  { code: "TPJ", name: "Tiruchchirapalli Jn" },
  { code: "TJ", name: "Thanjavur Jn" },
  { code: "ED", name: "Erode Jn" },
  { code: "SA", name: "Salem Jn" },
  { code: "TEN", name: "Tirunelveli Jn" },
  { code: "NCJ", name: "Nagercoil Jn" },
  { code: "KIK", name: "Kanyakumari" },
  { code: "RMM", name: "Rameswaram" },
  { code: "VRI", name: "Velankanni" },
  { code: "VLR", name: "Katpadi (Vellore)" },
  { code: "CGL", name: "Chengalpattu Jn" },
  { code: "PDY", name: "Puducherry" },
  { code: "VM", name: "Villupuram Jn" },

  // Kerala
  { code: "TVC", name: "Thiruvananthapuram Central" },
  { code: "ERS", name: "Ernakulam Jn" },
  { code: "ERN", name: "Ernakulam Town" },
  { code: "QLN", name: "Kollam Jn" },
  { code: "ALLP", name: "Alappuzha" },
  { code: "KTYM", name: "Kottayam" },
  { code: "TCR", name: "Thrissur" },
  { code: "CLT", name: "Kozhikode" },
  { code: "CAN", name: "Kannur" },
  { code: "PGT", name: "Palakkad Jn" },
  { code: "KGQ", name: "Kasaragod" },

  // Punjab, Haryana, Himachal, J&K
  { code: "ASR", name: "Amritsar Jn" },
  { code: "LDH", name: "Ludhiana Jn" },
  { code: "JUC", name: "Jalandhar City" },
  { code: "PTA", name: "Patiala" },
  { code: "BTI", name: "Bathinda Jn" },
  { code: "UMB", name: "Ambala Cantt" },
  { code: "CDG", name: "Chandigarh" },
  { code: "PNP", name: "Panipat Jn" },
  { code: "KKDE", name: "Kurukshetra Jn" },
  { code: "HSR", name: "Hisar" },
  { code: "RE", name: "Rewari Jn" },
  { code: "SVDK", name: "Shri Mata Vaishno Devi Katra" },
  { code: "JAT", name: "Jammu Tawi" },
  { code: "UHL", name: "Una Himachal" },
  { code: "PTK", name: "Pathankot Jn" },
  { code: "FZR", name: "Firozpur Cantt" },

  // Uttarakhand
  { code: "DDN", name: "Dehradun" },
  { code: "HW", name: "Haridwar Jn" },
  { code: "RKSH", name: "Rishikesh" },
  { code: "KGM", name: "Kathgodam" },
  { code: "RMR", name: "Ramnagar" },
  { code: "HRI", name: "Roorkee" },

  // Goa
  { code: "MAO", name: "Madgaon Jn" },
  { code: "KRMI", name: "Karmali" },
  { code: "VSG", name: "Vasco Da Gama" },

  // Misc important
  { code: "ED-1", name: "Latur" },
  { code: "WADI", name: "Wadi Jn" },
  { code: "GR", name: "Gulbarga (Kalaburagi)" },
  { code: "RC", name: "Raichur" },
];

export function generatePNR(): string {
  return Math.floor(1000000000 + Math.random() * 9000000000).toString();
}

export function generateSeat(classCode: string, index: number): string {
  const coachPrefix: Record<string, string> = {
    "1A": "H", "2A": "A", "3A": "B", "SL": "S", "CC": "C", "EC": "E",
  };
  const coach = (coachPrefix[classCode] ?? "B") + (1 + Math.floor(index / 64));
  const seatNum = 1 + (index % 64);
  return `${coach}-${seatNum}`;
}
