/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as BusesRouteImport } from './routes/buses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedBookingPnrRouteImport } from './routes/_authenticated/booking.$pnr'
import { Route as AuthenticatedBookTrainIdRouteImport } from './routes/_authenticated/book.$trainId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const BusesRoute = BusesRouteImport.update({
  id: '/buses',
  path: '/buses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingPnrRoute = AuthenticatedBookingPnrRouteImport.update({
  id: '/booking/$pnr',
  path: '/booking/$pnr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookTrainIdRoute =
  AuthenticatedBookTrainIdRouteImport.update({
    id: '/book/$trainId',
    path: '/book/$trainId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buses': typeof BusesRoute
  '/flights': typeof FlightsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/book/$trainId': typeof AuthenticatedBookTrainIdRoute
  '/booking/$pnr': typeof AuthenticatedBookingPnrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buses': typeof BusesRoute
  '/flights': typeof FlightsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/account': typeof AuthenticatedAccountRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/book/$trainId': typeof AuthenticatedBookTrainIdRoute
  '/booking/$pnr': typeof AuthenticatedBookingPnrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/buses': typeof BusesRoute
  '/flights': typeof FlightsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/book/$trainId': typeof AuthenticatedBookTrainIdRoute
  '/_authenticated/booking/$pnr': typeof AuthenticatedBookingPnrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buses'
    | '/flights'
    | '/reset-password'
    | '/search'
    | '/account'
    | '/bookings'
    | '/book/$trainId'
    | '/booking/$pnr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buses'
    | '/flights'
    | '/reset-password'
    | '/search'
    | '/account'
    | '/bookings'
    | '/book/$trainId'
    | '/booking/$pnr'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/buses'
    | '/flights'
    | '/reset-password'
    | '/search'
    | '/_authenticated/account'
    | '/_authenticated/bookings'
    | '/_authenticated/book/$trainId'
    | '/_authenticated/booking/$pnr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BusesRoute: typeof BusesRoute
  FlightsRoute: typeof FlightsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buses': {
      id: '/buses'
      path: '/buses'
      fullPath: '/buses'
      preLoaderRoute: typeof BusesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/booking/$pnr': {
      id: '/_authenticated/booking/$pnr'
      path: '/booking/$pnr'
      fullPath: '/booking/$pnr'
      preLoaderRoute: typeof AuthenticatedBookingPnrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/$trainId': {
      id: '/_authenticated/book/$trainId'
      path: '/book/$trainId'
      fullPath: '/book/$trainId'
      preLoaderRoute: typeof AuthenticatedBookTrainIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedBookTrainIdRoute: typeof AuthenticatedBookTrainIdRoute
  AuthenticatedBookingPnrRoute: typeof AuthenticatedBookingPnrRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedBookTrainIdRoute: AuthenticatedBookTrainIdRoute,
  AuthenticatedBookingPnrRoute: AuthenticatedBookingPnrRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BusesRoute: BusesRoute,
  FlightsRoute: FlightsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
